---
title: "Welcome"
subtitle: "Free R Data Science Workshop"
author: "Dr. Ajay Koli"
date: "31/01/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Dear participant,

\vspace{10mm}

It is my pleasure to welcome a total of thirty-nine participants who believe in me and registered for this beginner's course to learn about R.

Few important points:

- All sessions are absolutely free to attend.

- Strictly mute your microphone when you are not talking.

- All sessions will be conducted on Google Meet. Your email will be added to the Google Calender Event. You will receive an invitation acceptance email. Kindly accept the invitation to join the session.

- My only expectation is be polite, humble & respectful to each other during the sessions.

- I'm not promising but I'll try to include few practice exercises.

- Using a Google Form, you will be able to give your formal feedback at the end of the workshop.

- Session schedule is same as mentioned in the flyer

    - Mon - Wed - Fri
    - 20:00 - 21:00 IST
    - 1 Feb to 15 Feb, 2021

Please email if you have any specific query. I'm super excited to meet all of you and to have a wonderful learning experience. 

\vspace{15mm}

Your new friend,

Ajay  

Course website: https://r4b.netlify.app/  

Mobile: +91 88868 10879

Email: koliajaykumar@gmail.com

Linkedin: https://www.linkedin.com/in/ajay-kumar-koli-893702a4/
